### ISSUE TITLE
Problem while running python setup.py install

### ISSUE THREAD

**Issue by PaulMuadDib** [Hananel-Hazan/bindsnet#153]
Hi there
On windows 10, using Python 3.6.6 :: Anaconda custom (64-bit), I get the complaints below while installing bindsnet. Any idea ?

`D:\EEG_Signals\bindsnet-master>python setup.py install
D:\Anaconda3\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
running install
running bdist_egg
running egg_info
creating bindsnet.egg-info
writing bindsnet.egg-info\PKG-INFO
writing dependency_links to bindsnet.egg-info\dependency_links.txt
writing requirements to bindsnet.egg-info\requires.txt
writing top-level names to bindsnet.egg-info\top_level.txt
writing manifest file 'bindsnet.egg-info\SOURCES.txt'
reading manifest file 'bindsnet.egg-info\SOURCES.txt'
writing manifest file 'bindsnet.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build
creating build\lib
creating build\lib\bindsnet
copying bindsnet\utils.py -> build\lib\bindsnet
copying bindsnet\__init__.py -> build\lib\bindsnet
creating build\lib\bindsnet\analysis
copying bindsnet\analysis\plotting.py -> build\lib\bindsnet\analysis
copying bindsnet\analysis\visualization.py -> build\lib\bindsnet\analysis
copying bindsnet\analysis\__init__.py -> build\lib\bindsnet\analysis
creating build\lib\bindsnet\conversion
copying bindsnet\conversion\__init__.py -> build\lib\bindsnet\conversion
creating build\lib\bindsnet\datasets
copying bindsnet\datasets\preprocess.py -> build\lib\bindsnet\datasets
copying bindsnet\datasets\__init__.py -> build\lib\bindsnet\datasets
creating build\lib\bindsnet\encoding
copying bindsnet\encoding\__init__.py -> build\lib\bindsnet\encoding
creating build\lib\bindsnet\environment
copying bindsnet\environment\__init__.py -> build\lib\bindsnet\environment
creating build\lib\bindsnet\evaluation
copying bindsnet\evaluation\__init__.py -> build\lib\bindsnet\evaluation
creating build\lib\bindsnet\learning
copying bindsnet\learning\__init__.py -> build\lib\bindsnet\learning
creating build\lib\bindsnet\models
copying bindsnet\models\__init__.py -> build\lib\bindsnet\models
creating build\lib\bindsnet\network
copying bindsnet\network\monitors.py -> build\lib\bindsnet\network
copying bindsnet\network\nodes.py -> build\lib\bindsnet\network
copying bindsnet\network\topology.py -> build\lib\bindsnet\network
copying bindsnet\network\__init__.py -> build\lib\bindsnet\network
creating build\lib\bindsnet\pipeline
copying bindsnet\pipeline\action.py -> build\lib\bindsnet\pipeline
copying bindsnet\pipeline\__init__.py -> build\lib\bindsnet\pipeline
creating build\lib\bindsnet\preprocessing
copying bindsnet\preprocessing\__init__.py -> build\lib\bindsnet\preprocessing
creating build\bdist.win-amd64
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\bindsnet
creating build\bdist.win-amd64\egg\bindsnet\analysis
copying build\lib\bindsnet\analysis\plotting.py -> build\bdist.win-amd64\egg\bindsnet\analysis
copying build\lib\bindsnet\analysis\visualization.py -> build\bdist.win-amd64\egg\bindsnet\analysis
copying build\lib\bindsnet\analysis\__init__.py -> build\bdist.win-amd64\egg\bindsnet\analysis
creating build\bdist.win-amd64\egg\bindsnet\conversion
copying build\lib\bindsnet\conversion\__init__.py -> build\bdist.win-amd64\egg\bindsnet\conversion
creating build\bdist.win-amd64\egg\bindsnet\datasets
copying build\lib\bindsnet\datasets\preprocess.py -> build\bdist.win-amd64\egg\bindsnet\datasets
copying build\lib\bindsnet\datasets\__init__.py -> build\bdist.win-amd64\egg\bindsnet\datasets
creating build\bdist.win-amd64\egg\bindsnet\encoding
copying build\lib\bindsnet\encoding\__init__.py -> build\bdist.win-amd64\egg\bindsnet\encoding
creating build\bdist.win-amd64\egg\bindsnet\environment
copying build\lib\bindsnet\environment\__init__.py -> build\bdist.win-amd64\egg\bindsnet\environment
creating build\bdist.win-amd64\egg\bindsnet\evaluation
copying build\lib\bindsnet\evaluation\__init__.py -> build\bdist.win-amd64\egg\bindsnet\evaluation
creating build\bdist.win-amd64\egg\bindsnet\learning
copying build\lib\bindsnet\learning\__init__.py -> build\bdist.win-amd64\egg\bindsnet\learning
creating build\bdist.win-amd64\egg\bindsnet\models
copying build\lib\bindsnet\models\__init__.py -> build\bdist.win-amd64\egg\bindsnet\models
creating build\bdist.win-amd64\egg\bindsnet\network
copying build\lib\bindsnet\network\monitors.py -> build\bdist.win-amd64\egg\bindsnet\network
copying build\lib\bindsnet\network\nodes.py -> build\bdist.win-amd64\egg\bindsnet\network
copying build\lib\bindsnet\network\topology.py -> build\bdist.win-amd64\egg\bindsnet\network
copying build\lib\bindsnet\network\__init__.py -> build\bdist.win-amd64\egg\bindsnet\network
creating build\bdist.win-amd64\egg\bindsnet\pipeline
copying build\lib\bindsnet\pipeline\action.py -> build\bdist.win-amd64\egg\bindsnet\pipeline
copying build\lib\bindsnet\pipeline\__init__.py -> build\bdist.win-amd64\egg\bindsnet\pipeline
creating build\bdist.win-amd64\egg\bindsnet\preprocessing
copying build\lib\bindsnet\preprocessing\__init__.py -> build\bdist.win-amd64\egg\bindsnet\preprocessing
copying build\lib\bindsnet\utils.py -> build\bdist.win-amd64\egg\bindsnet
copying build\lib\bindsnet\__init__.py -> build\bdist.win-amd64\egg\bindsnet
byte-compiling build\bdist.win-amd64\egg\bindsnet\analysis\plotting.py to plotting.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\bindsnet\analysis\visualization.py to visualization.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\bindsnet\analysis\__init__.py to __init__.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\bindsnet\conversion\__init__.py to __init__.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\bindsnet\datasets\preprocess.py to preprocess.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\bindsnet\datasets\__init__.py to __init__.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\bindsnet\encoding\__init__.py to __init__.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\bindsnet\environment\__init__.py to __init__.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\bindsnet\evaluation\__init__.py to __init__.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\bindsnet\learning\__init__.py to __init__.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\bindsnet\models\__init__.py to __init__.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\bindsnet\network\monitors.py to monitors.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\bindsnet\network\nodes.py to nodes.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\bindsnet\network\topology.py to topology.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\bindsnet\network\__init__.py to __init__.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\bindsnet\pipeline\action.py to action.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\bindsnet\pipeline\__init__.py to __init__.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\bindsnet\preprocessing\__init__.py to __init__.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\bindsnet\utils.py to utils.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\bindsnet\__init__.py to __init__.cpython-36.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying bindsnet.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying bindsnet.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying bindsnet.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying bindsnet.egg-info\not-zip-safe -> build\bdist.win-amd64\egg\EGG-INFO
copying bindsnet.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying bindsnet.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
creating dist
creating 'dist\bindsnet-0.2.2-py3.6.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing bindsnet-0.2.2-py3.6.egg
creating d:\anaconda3\lib\site-packages\bindsnet-0.2.2-py3.6.egg
Extracting bindsnet-0.2.2-py3.6.egg to d:\anaconda3\lib\site-packages
Adding bindsnet 0.2.2 to easy-install.pth file

Installed d:\anaconda3\lib\site-packages\bindsnet-0.2.2-py3.6.egg
Processing dependencies for bindsnet==0.2.2
Searching for pyproj<=1.9.5.2
Downloading https://github.com/jswhit/pyproj/archive/429a4fe6fa404ba1bc1c0a88bee68c1a30a9b6f9.zip#egg=pyproj-1.9.5.2
Best match: pyproj 1.9.5.2
Processing 429a4fe6fa404ba1bc1c0a88bee68c1a30a9b6f9.zip
Writing C:\Users\Jeff\AppData\Local\Temp\easy_install-5_yfou7x\pyproj-429a4fe6fa404ba1bc1c0a88bee68c1a30a9b6f9\setup.cfg
Running pyproj-429a4fe6fa404ba1bc1c0a88bee68c1a30a9b6f9\setup.py -q bdist_egg --dist-dir C:\Users\Jeff\AppData\Local\Temp\easy_install-5_yfou7x\pyproj-429a4fe6fa404ba1bc1c0a88bee68c1a30a9b6f9\egg-dist-tmp-491v1zqx
using bundled proj4..
nad2bin.c
nad2bin.c(130): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
nad2bin.c(131): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
nad2bin.c(138): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
nad2bin.c(139): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
nad2bin.c(353): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
nad2bin.c(354): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
pj_malloc.c
Generating code
Finished generating code
executing C:\Users\Jeff\AppData\Local\Temp\easy_install-5_yfou7x\pyproj-429a4fe6fa404ba1bc1c0a88bee68c1a30a9b6f9\nad2bin lib\pyproj\data\alaska < datumgrid\alaska.lla
Output Binary File Format: ctable2
executing C:\Users\Jeff\AppData\Local\Temp\easy_install-5_yfou7x\pyproj-429a4fe6fa404ba1bc1c0a88bee68c1a30a9b6f9\nad2bin lib\pyproj\data\conus < datumgrid\conus.lla
Output Binary File Format: ctable2
executing C:\Users\Jeff\AppData\Local\Temp\easy_install-5_yfou7x\pyproj-429a4fe6fa404ba1bc1c0a88bee68c1a30a9b6f9\nad2bin lib\pyproj\data\FL < datumgrid\FL.lla
Output Binary File Format: ctable2
executing C:\Users\Jeff\AppData\Local\Temp\easy_install-5_yfou7x\pyproj-429a4fe6fa404ba1bc1c0a88bee68c1a30a9b6f9\nad2bin lib\pyproj\data\hawaii < datumgrid\hawaii.lla
Output Binary File Format: ctable2
executing C:\Users\Jeff\AppData\Local\Temp\easy_install-5_yfou7x\pyproj-429a4fe6fa404ba1bc1c0a88bee68c1a30a9b6f9\nad2bin lib\pyproj\data\MD < datumgrid\MD.lla
Output Binary File Format: ctable2
executing C:\Users\Jeff\AppData\Local\Temp\easy_install-5_yfou7x\pyproj-429a4fe6fa404ba1bc1c0a88bee68c1a30a9b6f9\nad2bin lib\pyproj\data\null < datumgrid\null.lla
Output Binary File Format: ctable2
executing C:\Users\Jeff\AppData\Local\Temp\easy_install-5_yfou7x\pyproj-429a4fe6fa404ba1bc1c0a88bee68c1a30a9b6f9\nad2bin lib\pyproj\data\prvi < datumgrid\prvi.lla
Output Binary File Format: ctable2
executing C:\Users\Jeff\AppData\Local\Temp\easy_install-5_yfou7x\pyproj-429a4fe6fa404ba1bc1c0a88bee68c1a30a9b6f9\nad2bin lib\pyproj\data\stgeorge < datumgrid\stgeorge.lla
Output Binary File Format: ctable2
executing C:\Users\Jeff\AppData\Local\Temp\easy_install-5_yfou7x\pyproj-429a4fe6fa404ba1bc1c0a88bee68c1a30a9b6f9\nad2bin lib\pyproj\data\stlrnc < datumgrid\stlrnc.lla
Output Binary File Format: ctable2
executing C:\Users\Jeff\AppData\Local\Temp\easy_install-5_yfou7x\pyproj-429a4fe6fa404ba1bc1c0a88bee68c1a30a9b6f9\nad2bin lib\pyproj\data\stpaul < datumgrid\stpaul.lla
Output Binary File Format: ctable2
executing C:\Users\Jeff\AppData\Local\Temp\easy_install-5_yfou7x\pyproj-429a4fe6fa404ba1bc1c0a88bee68c1a30a9b6f9\nad2bin lib\pyproj\data\TN < datumgrid\TN.lla
Output Binary File Format: ctable2
executing C:\Users\Jeff\AppData\Local\Temp\easy_install-5_yfou7x\pyproj-429a4fe6fa404ba1bc1c0a88bee68c1a30a9b6f9\nad2bin lib\pyproj\data\WI < datumgrid\WI.lla
Output Binary File Format: ctable2
executing C:\Users\Jeff\AppData\Local\Temp\easy_install-5_yfou7x\pyproj-429a4fe6fa404ba1bc1c0a88bee68c1a30a9b6f9\nad2bin lib\pyproj\data\WO < datumgrid\WO.lla
Output Binary File Format: ctable2
Compiling _proj.pyx because it changed.
[1/1] Cythonizing _proj.pyx
D:\Anaconda3\lib\site-packages\Cython\Compiler\Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\Jeff\AppData\Local\Temp\easy_install-5_yfou7x\pyproj-429a4fe6fa404ba1bc1c0a88bee68c1a30a9b6f9\_proj.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
warning: no files found matching 'src\*diff'
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
    yield saved
  File "D:\Anaconda3\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
    yield
  File "D:\Anaconda3\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "D:\Anaconda3\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "C:\Users\Jeff\AppData\Local\Temp\easy_install-5_yfou7x\pyproj-429a4fe6fa404ba1bc1c0a88bee68c1a30a9b6f9\setup.py", line 161, in <module>
  File "D:\Anaconda3\lib\site-packages\setuptools\__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "D:\Anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "D:\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "D:\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\Anaconda3\lib\site-packages\setuptools\command\bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "D:\Anaconda3\lib\site-packages\setuptools\command\bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "D:\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\Anaconda3\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "D:\Anaconda3\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "D:\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\Anaconda3\lib\site-packages\setuptools\command\build_ext.py", line 78, in run
    _build_ext.run(self)
  File "D:\Anaconda3\lib\distutils\command\build_ext.py", line 308, in run
    force=self.force)
  File "D:\Anaconda3\lib\distutils\ccompiler.py", line 1031, in new_compiler
    return klass(None, dry_run, force)
  File "D:\Anaconda3\lib\distutils\cygwinccompiler.py", line 285, in __init__
    CygwinCCompiler.__init__ (self, verbose, dry_run, force)
  File "D:\Anaconda3\lib\distutils\cygwinccompiler.py", line 129, in __init__
    if self.ld_version >= "2.10.90":
TypeError: '>=' not supported between instances of 'NoneType' and 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 27, in <module>
    'https://github.com/jswhit/pyproj/archive/429a4fe6fa404ba1bc1c0a88bee68c1a30a9b6f9.zip#egg=pyproj-1.9.5.2'
  File "D:\Anaconda3\lib\site-packages\setuptools\__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "D:\Anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "D:\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "D:\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\Anaconda3\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "D:\Anaconda3\lib\site-packages\setuptools\command\install.py", line 117, in do_egg_install
    cmd.run()
  File "D:\Anaconda3\lib\site-packages\setuptools\command\easy_install.py", line 412, in run
    self.easy_install(spec, not self.no_deps)
  File "D:\Anaconda3\lib\site-packages\setuptools\command\easy_install.py", line 654, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "D:\Anaconda3\lib\site-packages\setuptools\command\easy_install.py", line 701, in install_item
    self.process_distribution(spec, dist, deps)
  File "D:\Anaconda3\lib\site-packages\setuptools\command\easy_install.py", line 746, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "D:\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 774, in resolve
    replace_conflicting=replace_conflicting
  File "D:\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 1057, in best_match
    return self.obtain(req, installer)
  File "D:\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 1069, in obtain
    return installer(requirement)
  File "D:\Anaconda3\lib\site-packages\setuptools\command\easy_install.py", line 673, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "D:\Anaconda3\lib\site-packages\setuptools\command\easy_install.py", line 699, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "D:\Anaconda3\lib\site-packages\setuptools\command\easy_install.py", line 884, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "D:\Anaconda3\lib\site-packages\setuptools\command\easy_install.py", line 1152, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "D:\Anaconda3\lib\site-packages\setuptools\command\easy_install.py", line 1138, in run_setup
    run_setup(setup_script, args)
  File "D:\Anaconda3\lib\site-packages\setuptools\sandbox.py", line 253, in run_setup
    raise
  File "D:\Anaconda3\lib\contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "D:\Anaconda3\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
    yield
  File "D:\Anaconda3\lib\contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "D:\Anaconda3\lib\site-packages\setuptools\sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "D:\Anaconda3\lib\site-packages\setuptools\sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "D:\Anaconda3\lib\site-packages\setuptools\_vendor\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "D:\Anaconda3\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
    yield saved
  File "D:\Anaconda3\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
    yield
  File "D:\Anaconda3\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "D:\Anaconda3\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "C:\Users\Jeff\AppData\Local\Temp\easy_install-5_yfou7x\pyproj-429a4fe6fa404ba1bc1c0a88bee68c1a30a9b6f9\setup.py", line 161, in <module>
  File "D:\Anaconda3\lib\site-packages\setuptools\__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "D:\Anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "D:\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "D:\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\Anaconda3\lib\site-packages\setuptools\command\bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "D:\Anaconda3\lib\site-packages\setuptools\command\bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "D:\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\Anaconda3\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "D:\Anaconda3\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "D:\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\Anaconda3\lib\site-packages\setuptools\command\build_ext.py", line 78, in run
    _build_ext.run(self)
  File "D:\Anaconda3\lib\distutils\command\build_ext.py", line 308, in run
    force=self.force)
  File "D:\Anaconda3\lib\distutils\ccompiler.py", line 1031, in new_compiler
    return klass(None, dry_run, force)
  File "D:\Anaconda3\lib\distutils\cygwinccompiler.py", line 285, in __init__
    CygwinCCompiler.__init__ (self, verbose, dry_run, force)
  File "D:\Anaconda3\lib\distutils\cygwinccompiler.py", line 129, in __init__
    if self.ld_version >= "2.10.90":
TypeError: '>=' not supported between instances of 'NoneType' and 'str'
`

**Comment by djsaunde** [comment]
Hi @PaulMuadDib,

It looks like there's an issue installing pyproj (1.9.5.2). Can you try troubleshooting that?

I'll willing to try to reproduce this, but I won't have access to a Windows machine for a little while. Could you also try `pip install .` install of `python setup.py install` (just a sanity check)?

**Comment by PaulMuadDib** [comment]
I had first tried via `pip install` with the same result.
I am willing to dig into this.

**Comment by PaulMuadDib** [comment]
the setup went fine after the installation pyproj via Gohlke's binaries
https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyproj
