### ISSUE TITLE
Get error with using GPU for MNIST example

### ISSUE THREAD

**Issue by elliothe** [Hananel-Hazan/bindsnet#180]
When I wanna run the example code with GPU:
`python eth_mnist.py --gpu`
I get the following error:
```
Loading training images from serialized object file.

Loading training labels from serialized object file.


Begin training.

Progress: 0 / 60000 (0.0000 seconds)
Traceback (most recent call last):
  File "eth_mnist.py", line 128, in <module>
    sample = next(data_loader)
  File "/home/elliot/anaconda3/envs/pytorch_1.0/lib/python3.6/site-packages/bindsnet/encoding/__init__.py", line 108, in poisson_loader
    yield poisson(data[i], time)  # Encode datum as Poisson spike trains.
  File "/home/elliot/anaconda3/envs/pytorch_1.0/lib/python3.6/site-packages/bindsnet/encoding/__init__.py", line 75, in poisson
    datum = np.copy(datum)
  File "/home/elliot/anaconda3/envs/pytorch_1.0/lib/python3.6/site-packages/numpy/lib/function_base.py", line 792, in copy
    return array(a, order=order, copy=True)
  File "/home/elliot/anaconda3/envs/pytorch_1.0/lib/python3.6/site-packages/torch/tensor.py", line 450, in __array__
    return self.numpy()
TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
```

**Comment by Hananel-Hazan** [comment]
Hi @elliothe  Thank you for using BindsNET.

Unfortunately I'm not getting the error you got:
```
$ python3 eth_mnist.py --gpu

Loading training images from serialized object file.

Loading training labels from serialized object file.

Begin training.

Progress: 0 / 60000 (0.0000 seconds)
Progress: 10 / 60000 (10.3445 seconds)
```

Can you make sure that you running the latest version of PyTorch and BindsNET?
Also, please make sure that PyTorch using GPU properly using this [link](https://stackoverflow.com/questions/48152674/how-to-check-if-pytorch-is-using-the-gpu)

**Comment by elliothe** [comment]
Hi @Hananel-Hazan,
I did use the `pip install bindsnet` to install the bindsnet under the conda environment. 

There should be no problem for pytorch to use GPU.
```
Python 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 19:16:44)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.0.0'
>>> torch.cuda.current_device()
0
>>>
```

**Comment by elliothe** [comment]
I reinstall the bindsnet with the cloned repository, and it works. However, if I wanna enable the figure plot, the same error comes back.
```
python eth_mnist.py --plot --gpu
Loading training images from serialized object file.

Loading training labels from serialized object file.


Begin training.

Progress: 0 / 60000 (0.0000 seconds)
Traceback (most recent call last):
  File "eth_mnist.py", line 150, in <module>
    inpt_axes, inpt_ims = plot_input(images[i].view(28, 28), inpt, label=labels[i])
  File "/home/elliot/Documents/DRC_2019/bindsnet-master/bindsnet/analysis/plotting.py", line 32, in plot_input
    ims = axes[0].imshow(image, cmap='binary'), axes[1].imshow(inpt, cmap='binary')
  File "/home/elliot/anaconda3/envs/pytorch_1.0/lib/python3.6/site-packages/matplotlib/__init__.py", line 1805, in inner
    return func(ax, *args, **kwargs)
  File "/home/elliot/anaconda3/envs/pytorch_1.0/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 5483, in imshow
    im.set_data(X)
  File "/home/elliot/anaconda3/envs/pytorch_1.0/lib/python3.6/site-packages/matplotlib/image.py", line 638, in set_data
    self._A = cbook.safe_masked_invalid(A, copy=True)
  File "/home/elliot/anaconda3/envs/pytorch_1.0/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 784, in safe_masked_invalid
    x = np.array(x, subok=True, copy=copy)
  File "/home/elliot/anaconda3/envs/pytorch_1.0/lib/python3.6/site-packages/torch/tensor.py", line 450, in __array__
    return self.numpy()
TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copythe tensor to host memory first.
```
Morever, I found the code running on GPU is even slower than CPU version.

**Comment by Hananel-Hazan** [comment]
I pushed a fix to the plotting issue. Thank you for pointing it out

About the performance, the size of the network in this example is not enough to favorite GPU. CPU, in this case, will be faster (depending of course on the CPU model).
In much larger network, the GPU will be much faster.  For example see the benchmark in [link](https://www.frontiersin.org/articles/10.3389/fninf.2018.00089/full)
