### ISSUE TITLE
Testing with conv_mnist.py

### ISSUE THREAD

**Issue by lehahoang** [Hananel-Hazan/bindsnet#190]
Hello,
I simply tested the conv_mnist.py to see what to be shown but eventually I got this message:

Loading training labels from serialized object file.
Begin training.
Progress: 0 / 60000 (0.0000 seconds)
Traceback (most recent call last):
  File "conv_mnist.py", line 151, in <module>
    network.run(inpts=inpts, time=time) #, clamp=clamp)
  File "/homes/lhoang/anaconda3/lib/python3.7/site-packages/bindsnet/network/__init__.py", line 250, in run
    inpts.update(self.get_inputs())
  File "/homes/lhoang/anaconda3/lib/python3.7/site-packages/bindsnet/network/__init__.py", line 189, in get_inputs
    inpts[c[1]] += self.connections[c].compute(source.s)
  File "/homes/lhoang/anaconda3/lib/python3.7/site-packages/bindsnet/network/topology.py", line 153, in compute
    post = s.float().view(-1) @ self.w + self.b
RuntimeError: Expected tensor to have size 400 at dimension 1, but got size 4 for argument #2 'batch2' (while checking arguments for bmm)

As I am new to PyTorch, is there any solution to fix the problem?
Thank you.

**Comment by Hananel-Hazan** [comment]
What are the parameters that you tested? 
Have you change something in the example from the repo?

**Comment by djsaunde** [comment]
@Hananel-Hazan I got the same error without any changes. I'll try to fix it today if I have time.

**Comment by lehahoang** [comment]
Dear @Hananel-Hazan,
I haven't changed anything in the source code taken from the repo.
