### ISSUE TITLE
minimal_mnist.py results in AttributeError: 'numpy.ndarray' object has no attribute 'cpu'

### ISSUE THREAD

**Issue by amolk** [Hananel-Hazan/bindsnet#200]
On fresh setup, I get an error when running minimal_mnist example

```
➜ pip install -e .
...

➜ python --version
Python 3.6.5

➜ python minimal_mnist.py
Loading training images from serialized object file.

Loading training labels from serialized object file.

Traceback (most recent call last):
  File "minimal_mnist.py", line 17, in <module>
    encoding=poisson, time=350, plot_interval=1)
  File "/Users/amolk/work/bindsnet/bindsnet/pipeline/__init__.py", line 113, in __init__
    self.plot_data()
  File "/Users/amolk/work/bindsnet/bindsnet/pipeline/__init__.py", line 249, in plot_data
    self.voltage_record, plot_type=self.plot_type, threshold=self.threshold_value
  File "/Users/amolk/work/bindsnet/bindsnet/analysis/plotting.py", line 413, in plot_voltages
    v[1].cpu().numpy()[n_neurons[v[0]][0]:n_neurons[v[0]][1], time[0]:time[1]].cpu().numpy().T
AttributeError: 'numpy.ndarray' object has no attribute 'cpu'
```

**Comment by amolk** [comment]
I'll investigate and create a PR

**Comment by amolk** [comment]
@Hananel-Hazan Can you please give me access to create a PR?

**Comment by djsaunde** [comment]
You should be able to create a PR without any special access.

**Comment by amolk** [comment]
@djsaunde Daniel, here's what I get when I try to push the branch. Maybe I am missing something trivial? -

```
➜ git checkout 200
Already on '200'

➜ git log -n 1
commit 0c99ea3cc103a84ba47f9d1fb820ec128383925b (HEAD -> 200)
Author: Amol Kelkar <kelkar.amol@gmail.com>
Date:   Wed Feb 27 21:49:13 2019 -0800

    remove redundent cpu().numpy() on numpy tensor

➜ git push --set-upstream origin 200
remote: Permission to Hananel-Hazan/bindsnet.git denied to amolk.
fatal: unable to access 'https://github.com/Hananel-Hazan/bindsnet.git/': The requested URL returned error: 403
```

**Comment by djsaunde** [comment]
You should fork the project, make the changes, and then open the PR using the GitHub website

**Comment by amolk** [comment]
Okay, that's it. Thanks.
