### ISSUE TITLE
RuntimeError: Expected object of scalar type Long but got scalar type Float for argument #2 'mat2'

### ISSUE THREAD

**Issue by vankhoa21991** [Hananel-Hazan/bindsnet#201]
Hello, I ran the minimal_reservoir.py and got this error:
Loading training images from serialized object file.

Loading training labels from serialized object file.

Train progress: (50 / 500)
Train progress: (100 / 500)
Train progress: (150 / 500)
Train progress: (200 / 500)
Train progress: (250 / 500)
Train progress: (300 / 500)
Train progress: (350 / 500)
Train progress: (400 / 500)
Train progress: (450 / 500)
Train progress: (500 / 500)

Traceback (most recent call last):
  File "/home/kevin/IMRA_le/3_Program/SNN/bindsnet/examples/mnist/minimal_reservoir.py", line 52, in <module>
    output = model(s)
  File "/home/kevin/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kevin/IMRA_le/3_Program/SNN/bindsnet/examples/mnist/minimal_reservoir.py", line 19, in forward
    return self.linear(x)
  File "/home/kevin/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kevin/py36/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 67, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/kevin/py36/lib/python3.6/site-packages/torch/nn/functional.py", line 1354, in linear
    output = input.matmul(weight.t())
RuntimeError: Expected object of scalar type Long but got scalar type Float for argument #2 'mat2'

**Comment by djsaunde** [comment]
Hi @vankhoa21991, I fixed the bug in PR #203. Let me know if you have more issues.
