### ISSUE TITLE
missing the attribute: spike_record  From breakout_stdp.py

### ISSUE THREAD

**Issue by lianuo** [Hananel-Hazan/bindsnet#317]
Thanks for your excellent works! 
I tried your example breakout_stdp with the latest version 0.2.5 ,
python 3.7 pytorch1.2.
but got err as follow:
it seems that the spike_record does not exist in breakout compare to the mnist example.
------------------------------------
Training: 
Traceback (most recent call last):
  File "/home/guo/eng/snn/bindsnet/examples/breakout/breakout_stdp.py", line 74, in <module>
    run_pipeline(environment_pipeline, episode_count=100)
  File "/home/guo/eng/snn/bindsnet/examples/breakout/breakout_stdp.py", line 63, in run_pipeline
    result = pipeline.env_step()
  File "/home/guo/pro/ana3/lib/python3.7/site-packages/bindsnet/pipeline/environment_pipeline.py", line 120, in env_step
    self.action = self.action_function(self, output=self.output)
  File "/home/guo/pro/ana3/lib/python3.7/site-packages/bindsnet/pipeline/action.py", line 73, in select_softmax
    ), "EnvironmentPipeline is missing the attribute: spike_record."
AssertionError: EnvironmentPipeline is missing the attribute: spike_record.

**Comment by djsaunde** [comment]
@lianuo Thanks for the bug report. @sharath, I think you are familiar with this code, do you know what the issue is?

**Comment by lianuo** [comment]
thank you! it works now~
