### ISSUE TITLE
GPU/CPU error on breakout_stdp

### ISSUE THREAD

**Issue by alienatorZ** [Hananel-Hazan/bindsnet#325]
I tried running the breakout example breakout_stdp and recieved the following error...

Training: 
Traceback (most recent call last):
  File "c:\Users\Adam\.vscode\extensions\ms-python.python-2019.10.41019\pythonFiles\ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "c:\Users\Adam\.vscode\extensions\ms-python.python-2019.10.41019\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 432, in main
    run()
  File "c:\Users\Adam\.vscode\extensions\ms-python.python-2019.10.41019\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "C:\Users\Adam\.conda\envs\bindsnet\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\Adam\.conda\envs\bindsnet\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\Adam\.conda\envs\bindsnet\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\Adam\Downloads\bindsnet\examples\breakout\breakout_stdp.py", line 76, in <module>
    run_pipeline(environment_pipeline, episode_count=100)
  File "c:\Users\Adam\Downloads\bindsnet\examples\breakout\breakout_stdp.py", line 66, in run_pipeline
    pipeline.step(result)
  File "C:\Users\Adam\.conda\envs\bindsnet\lib\site-packages\bindsnet\pipeline\base_pipeline.py", line 130, in step
    step_out = self.step_(batch, **kwargs)
  File "C:\Users\Adam\.conda\envs\bindsnet\lib\site-packages\bindsnet\pipeline\environment_pipeline.py", line 164, in step_
    self.network.run(inpts=inpts, time=self.time, reward=reward, **kwargs)
  File "C:\Users\Adam\.conda\envs\bindsnet\lib\site-packages\bindsnet\network\network.py", line 379, in run
    mask=masks.get(c, None), learning=self.learning, **kwargs
  File "C:\Users\Adam\.conda\envs\bindsnet\lib\site-packages\bindsnet\network\topology.py", line 196, in update
    super().update(**kwargs)
  File "C:\Users\Adam\.conda\envs\bindsnet\lib\site-packages\bindsnet\network\topology.py", line 107, in update
    self.update_rule.update(**kwargs)
  File "C:\Users\Adam\.conda\envs\bindsnet\lib\site-packages\bindsnet\learning\learning.py", line 546, in _connection_update
    self.connection.w += self.nu[0] * self.reduction(update, dim=0)
RuntimeError: expected device cuda:0 but got device cpu

I am running Windows 10 with Nvidia GTX 1070.

Running the command torch.cuda.current_device() gives 0

**Comment by alienatorZ** [comment]
You were correct. I pulled the master branch. It seems like 0.2.1 is working correctly but just using the cpu. Is there documentation for using BindsNet with GPU?

I ran the test in the link and everything seems ok:
>>> import torch
>>> torch.cuda.device(0)
<torch.cuda.device object at 0x000001EBA8F97898>
>>> torch.cuda.device_count()
1
>>> torch.cuda.get_device_name(0)
'GeForce GTX 1070 with Max-Q Design'
>>> torch.cuda.is_available()
True

**Comment by djsaunde** [comment]
Hi @alienatorZ, using BindsNET with GPU is as simple as calling `network.to("cuda")`, where `network` is a `bindsnet.network.Network` object. When passing data to the network, it must be converted to the same device as the network with `tensor.gpu()`, where `tensor` is to be used as input to the network.

We don't currently have documentation for this, but it's a good idea to add a short tutorial on it in the [user manual](https://bindsnet-docs.readthedocs.io/guide.html).
