### ISSUE TITLE
Problem running the examples

### ISSUE THREAD

**Issue by Modatu** [Hananel-Hazan/bindsnet#80]
Hello everybody,

first off thank you for your efforts, I really like your approach.

I cloned the up-to-date version of your repo and tried your examples on a fresh aws deep learning ami.
My pytorch version is 0.4.0

When I run the eth_mnist.py example I get the following error:

```
Traceback (most recent call last):
  File "minimal_mnist.py", line 30, in <module>
    pipeline.step()
  File "/home/ubuntu/src/bindsnet/bindsnet/pipeline/__init__.py", line 150, in step
    clamp=clamp)
  File "/home/ubuntu/src/bindsnet/bindsnet/network/__init__.py", line 265, in run
    self.connections[c].normalize()
  File "/home/ubuntu/src/bindsnet/bindsnet/network/topology.py", line 166, in normalize
    self.w *= self.norm / self.w.sum(0).unsqueeze(-1)
RuntimeError: The expanded size of the tensor (784) must match the existing size (400) at non-singleton dimension 0
```

Thanks for your help!

Best regards,
Florian

**Comment by djsaunde** [comment]
Hi @Modatu,

Thanks for the bug report! I just pushed a fix for this bug (that was introduced just a few days ago!). The example script should work now.

Thanks,
Dan

**Comment by Modatu** [comment]
Thank you,
this fixes the issue for me!
